init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\myproject

install:
  - ps: |
      try {
      Install-Product node $env:nodejs_version $env:platform
      } catch {
      echo "Unable to install node $env:nodejs_version, trying update..."
      Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
      }
  - node -v
  - set GYP_MSVS_VERSION=2019
  - npm config set msvs_version 2019

configuration: Release

environment:
  matrix:
    # electron
    - nodejs_version: 16
      platform: x64
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 23.2.0
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 16
      platform: x86
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 23.2.0
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron

image: Visual Studio 2019
build_script: build.cmd

build: OFF
test: OFF
deploy: OFF
