init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\myproject

install:
  - ps: |
      try {
      Install-Product node $env:nodejs_version $env:platform
      } catch {
      echo "Unable to install node $env:nodejs_version, trying update..."
      Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
      }
  - node -v
  - set GYP_MSVS_VERSION=2019
  - npm config set msvs_version 2019
  - build.cmd

configuration: Release

environment:
  node_pre_gyp_github_token:
    secure: bjbQs3HtS0KGSj4BaH8BmQ0MhMHg0j00mIXXapOMtQs9CE7mkKDCfdm7C22CMItU
  matrix:
    # electron
    - nodejs_version: 14
      platform: x64
      PYTHON: "C:\\Python37-x64"
    - nodejs_version: 14
      platform: x86
      PYTHON: "C:\\Python37-x64"

image: Visual Studio 2019

build: OFF
test: OFF
deploy: OFF
