#ifdef _WIN32

#include <napi.h>
#include <Windows.h>
#include "./binding.h"



#define INIT_STATIC_METHOD(method) \
    TISGrabber::##method = GetProcAddress(tisgrabber, #method);

#define DEFINE_STATIC_METHOD(method)                                                                                  \
    if (TISGrabber::##method == NULL)                                                                                 \
    {                                                                                                                 \
        FreeLibrary(tisgrabber);                                                                                      \
        Napi::Error::New(env, "Cannot find function " #method " in tisgrabber_x64.dll").ThrowAsJavaScriptException(); \
        return exports;                                                                                               \
    }                                                                                                                 \
    properties.push_back(StaticMethod<&TISGrabber::##method>(#method, static_cast<napi_property_attributes>(napi_writable | napi_configurable), nullptr));

static HMODULE tisgrabber;

class TISGrabber : public Napi::ObjectWrap<TISGrabber>
{
public:
    static Napi::Object Init(Napi::Env env, Napi::Object exports);
    TISGrabber(const Napi::CallbackInfo &info);
    // ~TISGrabber();
    static IC_InitLibrary IC_InitLibrary;
    static IC_CreateGrabber IC_CreateGrabber;
    static IC_ReleaseGrabber IC_ReleaseGrabber;
    static IC_TidyUP IC_TidyUP;
    static IC_CloseLibrary IC_CloseLibrary;
    static IC_OpenVideoCaptureDevice IC_OpenVideoCaptureDevice;
    static IC_CloseVideoCaptureDevice IC_CloseVideoCaptureDevice;
    static IC_GetDeviceName IC_GetDeviceName;
    static IC_GetVideoFormatWidth IC_GetVideoFormatWidth;
    static IC_GetVideoFormatHeight IC_GetVideoFormatHeight;
    static IC_SetFormat IC_SetFormat;
    static IC_GetFormat IC_GetFormat;
    static IC_SetVideoFormat IC_SetVideoFormat;
    static IC_SetVideoNorm IC_SetVideoNorm;
    static IC_SetInputChannel IC_SetInputChannel;
    static IC_StartLive IC_StartLive;
    static IC_PrepareLive IC_PrepareLive;
    static IC_SuspendLive IC_SuspendLive;
    static IC_IsLive IC_IsLive;
    static IC_StopLive IC_StopLive;
    static IC_IsCameraPropertyAvailable IC_IsCameraPropertyAvailable;
    static IC_SetCameraProperty IC_SetCameraProperty;
    static IC_CameraPropertyGetRange IC_CameraPropertyGetRange;
    static IC_GetCameraProperty IC_GetCameraProperty;
    static IC_EnableAutoCameraProperty IC_EnableAutoCameraProperty;
    static IC_IsCameraPropertyAutoAvailable IC_IsCameraPropertyAutoAvailable;
    static IC_GetAutoCameraProperty IC_GetAutoCameraProperty;
    static IC_IsVideoPropertyAvailable IC_IsVideoPropertyAvailable;
    static IC_VideoPropertyGetRange IC_VideoPropertyGetRange;
    static IC_GetVideoProperty IC_GetVideoProperty;
    static IC_IsVideoPropertyAutoAvailable IC_IsVideoPropertyAutoAvailable;
    static IC_GetAutoVideoProperty IC_GetAutoVideoProperty;
    static IC_SetVideoProperty IC_SetVideoProperty;
    static IC_EnableAutoVideoProperty IC_EnableAutoVideoProperty;
    static IC_GetImageDescription IC_GetImageDescription;
    static IC_SnapImage IC_SnapImage;
    static IC_SaveImage IC_SaveImage;
    static IC_GetImagePtr IC_GetImagePtr;
    static IC_SetHWnd IC_SetHWnd;
    static IC_GetSerialNumber IC_GetSerialNumber;
    static IC_ListDevices IC_ListDevices;
    static IC_ListDevicesbyIndex IC_ListDevicesbyIndex;
    static IC_ListVideoFormats IC_ListVideoFormats;
    static IC_ListVideoFormatbyIndex IC_ListVideoFormatbyIndex;
    static IC_GetDeviceCount IC_GetDeviceCount;
    static IC_GetDevice IC_GetDevice;
    static IC_GetUniqueNamefromList IC_GetUniqueNamefromList;
    static IC_GetInputChannelCount IC_GetInputChannelCount;
    static IC_GetInputChannel IC_GetInputChannel;
    static IC_GetVideoNormCount IC_GetVideoNormCount;
    static IC_GetVideoNorm IC_GetVideoNorm;
    static IC_GetVideoFormatCount IC_GetVideoFormatCount;
    static IC_GetVideoFormat IC_GetVideoFormat;
    static IC_SaveDeviceStateToFile IC_SaveDeviceStateToFile;
    static IC_LoadDeviceStateFromFile IC_LoadDeviceStateFromFile;
    static IC_LoadDeviceStateFromFileEx IC_LoadDeviceStateFromFileEx;
    static IC_SaveDeviceSettings IC_SaveDeviceSettings;
    static IC_OpenDeviceBySettings IC_OpenDeviceBySettings;
    static IC_LoadDeviceSettings IC_LoadDeviceSettings;
    static IC_OpenDevByDisplayName IC_OpenDevByDisplayName;
    static IC_GetDisplayName IC_GetDisplayName;
    static IC_OpenDevByUniqueName IC_OpenDevByUniqueName;
    static IC_GetUniqueName IC_GetUniqueName;
    static IC_IsDevValid IC_IsDevValid;
    static IC_ShowPropertyDialog IC_ShowPropertyDialog;
    static IC_ShowDeviceSelectionDialog IC_ShowDeviceSelectionDialog;
    static IC_IsTriggerAvailable IC_IsTriggerAvailable;
    static IC_EnableTrigger IC_EnableTrigger;
    static IC_RemoveOverlay IC_RemoveOverlay;
    static IC_EnableOverlay IC_EnableOverlay;
    static IC_BeginPaint IC_BeginPaint;
    static IC_EndPaint IC_EndPaint;
    static IC_MsgBox IC_MsgBox;
    static IC_SetFrameReadyCallbackEx IC_SetFrameReadyCallbackEx;
    static IC_SetFrameReadyCallback IC_SetFrameReadyCallback;
    static IC_SetCallbacks IC_SetCallbacks;
    static IC_SetContinuousMode IC_SetContinuousMode;
    static IC_SetFrameRate IC_SetFrameRate;
    static IC_GetFrameRate IC_GetFrameRate;
    static IC_GetAvailableFrameRates IC_GetAvailableFrameRates;
    static IC_ShowInternalPropertyPage IC_ShowInternalPropertyPage;
    static IC_ResetUSBCam IC_ResetUSBCam;
    static IC_QueryPropertySet IC_QueryPropertySet;
    static IC_SetDefaultWindowPosition IC_SetDefaultWindowPosition;
    static IC_SetWindowPosition IC_SetWindowPosition;
    static IC_GetWindowPosition IC_GetWindowPosition;
    static IC_SetWhiteBalanceAuto IC_SetWhiteBalanceAuto;
    static IC_SignalDetected IC_SignalDetected;
    static IC_GetTriggerModes IC_GetTriggerModes;
    static IC_SetTriggerMode IC_SetTriggerMode;
    static IC_SetTriggerPolarity IC_SetTriggerPolarity;
    static IC_GetExpRegValRange IC_GetExpRegValRange;
    static IC_GetExpRegVal IC_GetExpRegVal;
    static IC_SetExpRegVal IC_SetExpRegVal;
    static IC_EnableExpRegValAuto IC_EnableExpRegValAuto;
    static IC_GetExpRegValAuto IC_GetExpRegValAuto;
    static IC_IsExpAbsValAvailable IC_IsExpAbsValAvailable;
    static IC_GetExpAbsValRange IC_GetExpAbsValRange;
    static IC_GetExpAbsVal IC_GetExpAbsVal;
    static IC_SetExpAbsVal IC_SetExpAbsVal;
    static IC_GetColorEnhancement IC_GetColorEnhancement;
    static IC_SetColorEnhancement IC_SetColorEnhancement;
    static IC_SoftwareTrigger IC_SoftwareTrigger;
    static IC_SetWhiteBalanceRed IC_SetWhiteBalanceRed;
    static IC_SetWhiteBalanceGreen IC_SetWhiteBalanceGreen;
    static IC_SetWhiteBalanceBlue IC_SetWhiteBalanceBlue;
    static IC_FocusOnePush IC_FocusOnePush;
    static IC_enumProperties IC_enumProperties;
    static IC_printItemandElementNames IC_printItemandElementNames;
    static IC_enumPropertyElements IC_enumPropertyElements;
    static IC_enumPropertyElementInterfaces IC_enumPropertyElementInterfaces;
    static IC_IsPropertyAvailable IC_IsPropertyAvailable;
    static IC_GetPropertyValueRange IC_GetPropertyValueRange;
    static IC_GetPropertyValue IC_GetPropertyValue;
    static IC_SetPropertyValue IC_SetPropertyValue;
    static IC_GetPropertyAbsoluteValueRange IC_GetPropertyAbsoluteValueRange;
    static IC_GetPropertyAbsoluteValue IC_GetPropertyAbsoluteValue;
    static IC_SetPropertyAbsoluteValue IC_SetPropertyAbsoluteValue;
    static IC_GetPropertySwitch IC_GetPropertySwitch;
    static IC_SetPropertySwitch IC_SetPropertySwitch;
    static IC_PropertyOnePush IC_PropertyOnePush;
    static IC_GetPropertyMapStrings IC_GetPropertyMapStrings;
    static IC_GetPropertyMapString IC_GetPropertyMapString;
    static IC_SetPropertyMapString IC_SetPropertyMapString;
    static IC_ResetProperties IC_ResetProperties;
    static IC_GetAvailableFrameFilterCount IC_GetAvailableFrameFilterCount;
    static IC_GetAvailableFrameFilters IC_GetAvailableFrameFilters;
    static IC_CreateFrameFilter IC_CreateFrameFilter;
    static IC_AddFrameFilterToDevice IC_AddFrameFilterToDevice;
    static IC_RemoveFrameFilterFromDevice IC_RemoveFrameFilterFromDevice;
    static IC_DeleteFrameFilter IC_DeleteFrameFilter;
    static IC_FrameFilterShowDialog IC_FrameFilterShowDialog;
    static IC_FrameFilterGetParameter IC_FrameFilterGetParameter;
    static IC_FrameFilterSetParameterInt IC_FrameFilterSetParameterInt;
    static IC_FrameFilterSetParameterFloat IC_FrameFilterSetParameterFloat;
    static IC_FrameFilterSetParameterBoolean IC_FrameFilterSetParameterBoolean;
    static IC_FrameFilterSetParameterString IC_FrameFilterSetParameterString;
    static IC_FrameFilterDeviceClear IC_FrameFilterDeviceClear;
    static IC_enumCodecs IC_enumCodecs;
    static IC_Codec_Create IC_Codec_Create;
    static IC_Codec_Release IC_Codec_Release;
    static IC_Codec_getName IC_Codec_getName;
    static IC_Codec_hasDialog IC_Codec_hasDialog;
    static IC_Codec_showDialog IC_Codec_showDialog;
    static IC_SetCodec IC_SetCodec;
    static IC_SetAVIFileName IC_SetAVIFileName;
    static IC_enableAVICapturePause IC_enableAVICapturePause;
    static IC_SetRingBufferSize IC_SetRingBufferSize;
    static IC_GetRingBufferSize IC_GetRingBufferSize;
    static IC_GetMemBuffer IC_GetMemBuffer;
    static IC_GetMemBufferLastAcq IC_GetMemBufferLastAcq;
    static IC_ReleaseMemBuffer IC_ReleaseMemBuffer;
    static IC_GetMemBufferDescription IC_GetMemBufferDescription;
    static IC_MemBufferLock IC_MemBufferLock;
    static IC_MemBufferisLocked IC_MemBufferisLocked;
    static IC_MemBufferGetIndex IC_MemBufferGetIndex;
    static IC_MemBufferGetDataPtr IC_MemBufferGetDataPtr;
    // HGRABBER m_hgrabber;
};

Napi::Object TISGrabber::Init(Napi::Env env, Napi::Object exports)
{
    // 加载动态库
    tisgrabber = LoadLibrary("tisgrabber_x64.dll");
    if (tisgrabber == NULL)
    {
        Napi::Error::New(env, "Cannot load tisgrabber_x64.dll").ThrowAsJavaScriptException();
        return exports;
    }
    std::vector<Napi::ClassPropertyDescriptor<TISGrabber>> properties = {};
    if (TISGrabber::IC_InitLibrary == NULL)
    {
        FreeLibrary(tisgrabber);
        Napi::Error::New(env, "Cannot find function IC_InitLibrary in tisgrabber_x64.dll").ThrowAsJavaScriptException();
        return exports;
    }
    properties.push_back(StaticMethod<&TISGrabber::IC_InitLibrary>("IC_InitLibrary", static_cast<napi_property_attributes>(napi_writable | napi_configurable), (void*)nullptr));
    // DEFINE_STATIC_METHOD(IC_InitLibrary);
    // DEFINE_STATIC_METHOD(IC_CreateGrabber);
    // DEFINE_STATIC_METHOD(IC_ReleaseGrabber);
    // DEFINE_STATIC_METHOD(IC_TidyUP);
    // DEFINE_STATIC_METHOD(IC_CloseLibrary);
    // DEFINE_STATIC_METHOD(IC_OpenVideoCaptureDevice);
    // DEFINE_STATIC_METHOD(IC_CloseVideoCaptureDevice);
    // DEFINE_STATIC_METHOD(IC_GetDeviceName);
    // DEFINE_STATIC_METHOD(IC_GetVideoFormatWidth);
    // DEFINE_STATIC_METHOD(IC_GetVideoFormatHeight);
    // DEFINE_STATIC_METHOD(IC_SetFormat);
    // DEFINE_STATIC_METHOD(IC_GetFormat);
    // DEFINE_STATIC_METHOD(IC_SetVideoFormat);
    // DEFINE_STATIC_METHOD(IC_SetVideoNorm);
    // DEFINE_STATIC_METHOD(IC_SetInputChannel);
    // DEFINE_STATIC_METHOD(IC_StartLive);
    // DEFINE_STATIC_METHOD(IC_PrepareLive);
    // DEFINE_STATIC_METHOD(IC_SuspendLive);
    // DEFINE_STATIC_METHOD(IC_IsLive);
    // DEFINE_STATIC_METHOD(IC_StopLive);
    // DEFINE_STATIC_METHOD(IC_IsCameraPropertyAvailable);
    // DEFINE_STATIC_METHOD(IC_SetCameraProperty);
    // DEFINE_STATIC_METHOD(IC_CameraPropertyGetRange);
    // DEFINE_STATIC_METHOD(IC_GetCameraProperty);
    // DEFINE_STATIC_METHOD(IC_EnableAutoCameraProperty);
    // DEFINE_STATIC_METHOD(IC_IsCameraPropertyAutoAvailable);
    // DEFINE_STATIC_METHOD(IC_GetAutoCameraProperty);
    // DEFINE_STATIC_METHOD(IC_IsVideoPropertyAvailable);
    // DEFINE_STATIC_METHOD(IC_VideoPropertyGetRange);
    // DEFINE_STATIC_METHOD(IC_GetVideoProperty);
    // DEFINE_STATIC_METHOD(IC_IsVideoPropertyAutoAvailable);
    // DEFINE_STATIC_METHOD(IC_GetAutoVideoProperty);
    // DEFINE_STATIC_METHOD(IC_SetVideoProperty);
    // DEFINE_STATIC_METHOD(IC_EnableAutoVideoProperty);
    // DEFINE_STATIC_METHOD(IC_GetImageDescription);
    // DEFINE_STATIC_METHOD(IC_SnapImage);
    // DEFINE_STATIC_METHOD(IC_SaveImage);
    // DEFINE_STATIC_METHOD(IC_GetImagePtr);
    // DEFINE_STATIC_METHOD(IC_SetHWnd);
    // DEFINE_STATIC_METHOD(IC_GetSerialNumber);
    // DEFINE_STATIC_METHOD(IC_ListDevices);
    // DEFINE_STATIC_METHOD(IC_ListDevicesbyIndex);
    // DEFINE_STATIC_METHOD(IC_ListVideoFormats);
    // DEFINE_STATIC_METHOD(IC_ListVideoFormatbyIndex);
    // DEFINE_STATIC_METHOD(IC_GetDeviceCount);
    // DEFINE_STATIC_METHOD(IC_GetDevice);
    // DEFINE_STATIC_METHOD(IC_GetUniqueNamefromList);
    // DEFINE_STATIC_METHOD(IC_GetInputChannelCount);
    // DEFINE_STATIC_METHOD(IC_GetInputChannel);
    // DEFINE_STATIC_METHOD(IC_GetVideoNormCount);
    // DEFINE_STATIC_METHOD(IC_GetVideoNorm);
    // DEFINE_STATIC_METHOD(IC_GetVideoFormatCount);
    // DEFINE_STATIC_METHOD(IC_GetVideoFormat);
    // DEFINE_STATIC_METHOD(IC_SaveDeviceStateToFile);
    // DEFINE_STATIC_METHOD(IC_LoadDeviceStateFromFile);
    // DEFINE_STATIC_METHOD(IC_LoadDeviceStateFromFileEx);
    // DEFINE_STATIC_METHOD(IC_SaveDeviceSettings);
    // DEFINE_STATIC_METHOD(IC_OpenDeviceBySettings);
    // DEFINE_STATIC_METHOD(IC_LoadDeviceSettings);
    // DEFINE_STATIC_METHOD(IC_OpenDevByDisplayName);
    // DEFINE_STATIC_METHOD(IC_GetDisplayName);
    // DEFINE_STATIC_METHOD(IC_OpenDevByUniqueName);
    // DEFINE_STATIC_METHOD(IC_GetUniqueName);
    // DEFINE_STATIC_METHOD(IC_IsDevValid);
    // DEFINE_STATIC_METHOD(IC_ShowPropertyDialog);
    // DEFINE_STATIC_METHOD(IC_ShowDeviceSelectionDialog);
    // DEFINE_STATIC_METHOD(IC_IsTriggerAvailable);
    // DEFINE_STATIC_METHOD(IC_EnableTrigger);
    // DEFINE_STATIC_METHOD(IC_RemoveOverlay);
    // DEFINE_STATIC_METHOD(IC_EnableOverlay);
    // DEFINE_STATIC_METHOD(IC_BeginPaint);
    // DEFINE_STATIC_METHOD(IC_EndPaint);
    // DEFINE_STATIC_METHOD(IC_MsgBox);
    // DEFINE_STATIC_METHOD(IC_SetFrameReadyCallbackEx);
    // DEFINE_STATIC_METHOD(IC_SetFrameReadyCallback);
    // DEFINE_STATIC_METHOD(IC_SetCallbacks);
    // DEFINE_STATIC_METHOD(IC_SetContinuousMode);
    // DEFINE_STATIC_METHOD(IC_SetFrameRate);
    // DEFINE_STATIC_METHOD(IC_GetFrameRate);
    // DEFINE_STATIC_METHOD(IC_GetAvailableFrameRates);
    // DEFINE_STATIC_METHOD(IC_ShowInternalPropertyPage);
    // DEFINE_STATIC_METHOD(IC_ResetUSBCam);
    // DEFINE_STATIC_METHOD(IC_QueryPropertySet);
    // DEFINE_STATIC_METHOD(IC_SetDefaultWindowPosition);
    // DEFINE_STATIC_METHOD(IC_SetWindowPosition);
    // DEFINE_STATIC_METHOD(IC_GetWindowPosition);
    // DEFINE_STATIC_METHOD(IC_SetWhiteBalanceAuto);
    // DEFINE_STATIC_METHOD(IC_SignalDetected);
    // DEFINE_STATIC_METHOD(IC_GetTriggerModes);
    // DEFINE_STATIC_METHOD(IC_SetTriggerMode);
    // DEFINE_STATIC_METHOD(IC_SetTriggerPolarity);
    // DEFINE_STATIC_METHOD(IC_GetExpRegValRange);
    // DEFINE_STATIC_METHOD(IC_GetExpRegVal);
    // DEFINE_STATIC_METHOD(IC_SetExpRegVal);
    // DEFINE_STATIC_METHOD(IC_EnableExpRegValAuto);
    // DEFINE_STATIC_METHOD(IC_GetExpRegValAuto);
    // DEFINE_STATIC_METHOD(IC_IsExpAbsValAvailable);
    // DEFINE_STATIC_METHOD(IC_GetExpAbsValRange);
    // DEFINE_STATIC_METHOD(IC_GetExpAbsVal);
    // DEFINE_STATIC_METHOD(IC_SetExpAbsVal);
    // DEFINE_STATIC_METHOD(IC_GetColorEnhancement);
    // DEFINE_STATIC_METHOD(IC_SetColorEnhancement);
    // DEFINE_STATIC_METHOD(IC_SoftwareTrigger);
    // DEFINE_STATIC_METHOD(IC_SetWhiteBalanceRed);
    // DEFINE_STATIC_METHOD(IC_SetWhiteBalanceGreen);
    // DEFINE_STATIC_METHOD(IC_SetWhiteBalanceBlue);
    // DEFINE_STATIC_METHOD(IC_FocusOnePush);
    // DEFINE_STATIC_METHOD(IC_enumProperties);
    // DEFINE_STATIC_METHOD(IC_printItemandElementNames);
    // DEFINE_STATIC_METHOD(IC_enumPropertyElements);
    // DEFINE_STATIC_METHOD(IC_enumPropertyElementInterfaces);
    // DEFINE_STATIC_METHOD(IC_IsPropertyAvailable);
    // DEFINE_STATIC_METHOD(IC_GetPropertyValueRange);
    // DEFINE_STATIC_METHOD(IC_GetPropertyValue);
    // DEFINE_STATIC_METHOD(IC_SetPropertyValue);
    // DEFINE_STATIC_METHOD(IC_GetPropertyAbsoluteValueRange);
    // DEFINE_STATIC_METHOD(IC_GetPropertyAbsoluteValue);
    // DEFINE_STATIC_METHOD(IC_SetPropertyAbsoluteValue);
    // DEFINE_STATIC_METHOD(IC_GetPropertySwitch);
    // DEFINE_STATIC_METHOD(IC_SetPropertySwitch);
    // DEFINE_STATIC_METHOD(IC_PropertyOnePush);
    // DEFINE_STATIC_METHOD(IC_GetPropertyMapStrings);
    // DEFINE_STATIC_METHOD(IC_GetPropertyMapString);
    // DEFINE_STATIC_METHOD(IC_SetPropertyMapString);
    // DEFINE_STATIC_METHOD(IC_ResetProperties);
    // DEFINE_STATIC_METHOD(IC_GetAvailableFrameFilterCount);
    // DEFINE_STATIC_METHOD(IC_GetAvailableFrameFilters);
    // DEFINE_STATIC_METHOD(IC_CreateFrameFilter);
    // DEFINE_STATIC_METHOD(IC_AddFrameFilterToDevice);
    // DEFINE_STATIC_METHOD(IC_RemoveFrameFilterFromDevice);
    // DEFINE_STATIC_METHOD(IC_DeleteFrameFilter);
    // DEFINE_STATIC_METHOD(IC_FrameFilterShowDialog);
    // DEFINE_STATIC_METHOD(IC_FrameFilterGetParameter);
    // DEFINE_STATIC_METHOD(IC_FrameFilterSetParameterInt);
    // DEFINE_STATIC_METHOD(IC_FrameFilterSetParameterFloat);
    // DEFINE_STATIC_METHOD(IC_FrameFilterSetParameterBoolean);
    // DEFINE_STATIC_METHOD(IC_FrameFilterSetParameterString);
    // DEFINE_STATIC_METHOD(IC_FrameFilterDeviceClear);
    // DEFINE_STATIC_METHOD(IC_enumCodecs);
    // DEFINE_STATIC_METHOD(IC_Codec_Create);
    // DEFINE_STATIC_METHOD(IC_Codec_Release);
    // DEFINE_STATIC_METHOD(IC_Codec_getName);
    // DEFINE_STATIC_METHOD(IC_Codec_hasDialog);
    // DEFINE_STATIC_METHOD(IC_Codec_showDialog);
    // DEFINE_STATIC_METHOD(IC_SetCodec);
    // DEFINE_STATIC_METHOD(IC_SetAVIFileName);
    // DEFINE_STATIC_METHOD(IC_enableAVICapturePause);
    // DEFINE_STATIC_METHOD(IC_SetRingBufferSize);
    // DEFINE_STATIC_METHOD(IC_GetRingBufferSize);
    // DEFINE_STATIC_METHOD(IC_GetMemBuffer);
    // DEFINE_STATIC_METHOD(IC_GetMemBufferLastAcq);
    // DEFINE_STATIC_METHOD(IC_ReleaseMemBuffer);
    // DEFINE_STATIC_METHOD(IC_GetMemBufferDescription);
    // DEFINE_STATIC_METHOD(IC_MemBufferLock);
    // DEFINE_STATIC_METHOD(IC_MemBufferisLocked);
    // DEFINE_STATIC_METHOD(IC_MemBufferGetIndex);
    // DEFINE_STATIC_METHOD(IC_MemBufferGetDataPtr);

    Napi::Function func = DefineClass(env, "TISGrabber", properties);
    Napi::FunctionReference *constructor = new Napi::FunctionReference();
    *constructor = Napi::Persistent(func);

    exports.Set("TISGrabber", func);
    return exports;
}

// TISGrabber::TISGrabber(const Napi::CallbackInfo &info) : Napi::ObjectWrap<TISGrabber>(info)
// {
//     Napi::String unique_name = info[0].As<Napi::String>();
//     m_hgrabber = IC_CreateGrabber();
//     TISGrabber::IC_OpenDevByUniqueName(m_hgrabber, unique_name.Utf8Value().c_str());
// }

// TISGrabber::~TISGrabber()
// {
//     IC_ReleaseGrabber(&m_hgrabber);
// }

 TISGrabber::IC_InitLibrary = GetProcAddress(tisgrabber, "IC_InitLibrary");

// INIT_STATIC_METHOD(IC_InitLibrary);
// INIT_STATIC_METHOD(IC_CreateGrabber);
// INIT_STATIC_METHOD(IC_ReleaseGrabber);
// INIT_STATIC_METHOD(IC_TidyUP);
// INIT_STATIC_METHOD(IC_CloseLibrary);
// INIT_STATIC_METHOD(IC_OpenVideoCaptureDevice);
// INIT_STATIC_METHOD(IC_CloseVideoCaptureDevice);
// INIT_STATIC_METHOD(IC_GetDeviceName);
// INIT_STATIC_METHOD(IC_GetVideoFormatWidth);
// INIT_STATIC_METHOD(IC_GetVideoFormatHeight);
// INIT_STATIC_METHOD(IC_SetFormat);
// INIT_STATIC_METHOD(IC_GetFormat);
// INIT_STATIC_METHOD(IC_SetVideoFormat);
// INIT_STATIC_METHOD(IC_SetVideoNorm);
// INIT_STATIC_METHOD(IC_SetInputChannel);
// INIT_STATIC_METHOD(IC_StartLive);
// INIT_STATIC_METHOD(IC_PrepareLive);
// INIT_STATIC_METHOD(IC_SuspendLive);
// INIT_STATIC_METHOD(IC_IsLive);
// INIT_STATIC_METHOD(IC_StopLive);
// INIT_STATIC_METHOD(IC_IsCameraPropertyAvailable);
// INIT_STATIC_METHOD(IC_SetCameraProperty);
// INIT_STATIC_METHOD(IC_CameraPropertyGetRange);
// INIT_STATIC_METHOD(IC_GetCameraProperty);
// INIT_STATIC_METHOD(IC_EnableAutoCameraProperty);
// INIT_STATIC_METHOD(IC_IsCameraPropertyAutoAvailable);
// INIT_STATIC_METHOD(IC_GetAutoCameraProperty);
// INIT_STATIC_METHOD(IC_IsVideoPropertyAvailable);
// INIT_STATIC_METHOD(IC_VideoPropertyGetRange);
// INIT_STATIC_METHOD(IC_GetVideoProperty);
// INIT_STATIC_METHOD(IC_IsVideoPropertyAutoAvailable);
// INIT_STATIC_METHOD(IC_GetAutoVideoProperty);
// INIT_STATIC_METHOD(IC_SetVideoProperty);
// INIT_STATIC_METHOD(IC_EnableAutoVideoProperty);
// INIT_STATIC_METHOD(IC_GetImageDescription);
// INIT_STATIC_METHOD(IC_SnapImage);
// INIT_STATIC_METHOD(IC_SaveImage);
// INIT_STATIC_METHOD(IC_GetImagePtr);
// INIT_STATIC_METHOD(IC_SetHWnd);
// INIT_STATIC_METHOD(IC_GetSerialNumber);
// INIT_STATIC_METHOD(IC_ListDevices);
// INIT_STATIC_METHOD(IC_ListDevicesbyIndex);
// INIT_STATIC_METHOD(IC_ListVideoFormats);
// INIT_STATIC_METHOD(IC_ListVideoFormatbyIndex);
// INIT_STATIC_METHOD(IC_GetDeviceCount);
// INIT_STATIC_METHOD(IC_GetDevice);
// INIT_STATIC_METHOD(IC_GetUniqueNamefromList);
// INIT_STATIC_METHOD(IC_GetInputChannelCount);
// INIT_STATIC_METHOD(IC_GetInputChannel);
// INIT_STATIC_METHOD(IC_GetVideoNormCount);
// INIT_STATIC_METHOD(IC_GetVideoNorm);
// INIT_STATIC_METHOD(IC_GetVideoFormatCount);
// INIT_STATIC_METHOD(IC_GetVideoFormat);
// INIT_STATIC_METHOD(IC_SaveDeviceStateToFile);
// INIT_STATIC_METHOD(IC_LoadDeviceStateFromFile);
// INIT_STATIC_METHOD(IC_LoadDeviceStateFromFileEx);
// INIT_STATIC_METHOD(IC_SaveDeviceSettings);
// INIT_STATIC_METHOD(IC_OpenDeviceBySettings);
// INIT_STATIC_METHOD(IC_LoadDeviceSettings);
// INIT_STATIC_METHOD(IC_OpenDevByDisplayName);
// INIT_STATIC_METHOD(IC_GetDisplayName);
// INIT_STATIC_METHOD(IC_OpenDevByUniqueName);
// INIT_STATIC_METHOD(IC_GetUniqueName);
// INIT_STATIC_METHOD(IC_IsDevValid);
// INIT_STATIC_METHOD(IC_ShowPropertyDialog);
// INIT_STATIC_METHOD(IC_ShowDeviceSelectionDialog);
// INIT_STATIC_METHOD(IC_IsTriggerAvailable);
// INIT_STATIC_METHOD(IC_EnableTrigger);
// INIT_STATIC_METHOD(IC_RemoveOverlay);
// INIT_STATIC_METHOD(IC_EnableOverlay);
// INIT_STATIC_METHOD(IC_BeginPaint);
// INIT_STATIC_METHOD(IC_EndPaint);
// INIT_STATIC_METHOD(IC_MsgBox);
// INIT_STATIC_METHOD(IC_SetFrameReadyCallbackEx);
// INIT_STATIC_METHOD(IC_SetFrameReadyCallback);
// INIT_STATIC_METHOD(IC_SetCallbacks);
// INIT_STATIC_METHOD(IC_SetContinuousMode);
// INIT_STATIC_METHOD(IC_SetFrameRate);
// INIT_STATIC_METHOD(IC_GetFrameRate);
// INIT_STATIC_METHOD(IC_GetAvailableFrameRates);
// INIT_STATIC_METHOD(IC_ShowInternalPropertyPage);
// INIT_STATIC_METHOD(IC_ResetUSBCam);
// INIT_STATIC_METHOD(IC_QueryPropertySet);
// INIT_STATIC_METHOD(IC_SetDefaultWindowPosition);
// INIT_STATIC_METHOD(IC_SetWindowPosition);
// INIT_STATIC_METHOD(IC_GetWindowPosition);
// INIT_STATIC_METHOD(IC_SetWhiteBalanceAuto);
// INIT_STATIC_METHOD(IC_SignalDetected);
// INIT_STATIC_METHOD(IC_GetTriggerModes);
// INIT_STATIC_METHOD(IC_SetTriggerMode);
// INIT_STATIC_METHOD(IC_SetTriggerPolarity);
// INIT_STATIC_METHOD(IC_GetExpRegValRange);
// INIT_STATIC_METHOD(IC_GetExpRegVal);
// INIT_STATIC_METHOD(IC_SetExpRegVal);
// INIT_STATIC_METHOD(IC_EnableExpRegValAuto);
// INIT_STATIC_METHOD(IC_GetExpRegValAuto);
// INIT_STATIC_METHOD(IC_IsExpAbsValAvailable);
// INIT_STATIC_METHOD(IC_GetExpAbsValRange);
// INIT_STATIC_METHOD(IC_GetExpAbsVal);
// INIT_STATIC_METHOD(IC_SetExpAbsVal);
// INIT_STATIC_METHOD(IC_GetColorEnhancement);
// INIT_STATIC_METHOD(IC_SetColorEnhancement);
// INIT_STATIC_METHOD(IC_SoftwareTrigger);
// INIT_STATIC_METHOD(IC_SetWhiteBalanceRed);
// INIT_STATIC_METHOD(IC_SetWhiteBalanceGreen);
// INIT_STATIC_METHOD(IC_SetWhiteBalanceBlue);
// INIT_STATIC_METHOD(IC_FocusOnePush);
// INIT_STATIC_METHOD(IC_enumProperties);
// INIT_STATIC_METHOD(IC_printItemandElementNames);
// INIT_STATIC_METHOD(IC_enumPropertyElements);
// INIT_STATIC_METHOD(IC_enumPropertyElementInterfaces);
// INIT_STATIC_METHOD(IC_IsPropertyAvailable);
// INIT_STATIC_METHOD(IC_GetPropertyValueRange);
// INIT_STATIC_METHOD(IC_GetPropertyValue);
// INIT_STATIC_METHOD(IC_SetPropertyValue);
// INIT_STATIC_METHOD(IC_GetPropertyAbsoluteValueRange);
// INIT_STATIC_METHOD(IC_GetPropertyAbsoluteValue);
// INIT_STATIC_METHOD(IC_SetPropertyAbsoluteValue);
// INIT_STATIC_METHOD(IC_GetPropertySwitch);
// INIT_STATIC_METHOD(IC_SetPropertySwitch);
// INIT_STATIC_METHOD(IC_PropertyOnePush);
// INIT_STATIC_METHOD(IC_GetPropertyMapStrings);
// INIT_STATIC_METHOD(IC_GetPropertyMapString);
// INIT_STATIC_METHOD(IC_SetPropertyMapString);
// INIT_STATIC_METHOD(IC_ResetProperties);
// INIT_STATIC_METHOD(IC_GetAvailableFrameFilterCount);
// INIT_STATIC_METHOD(IC_GetAvailableFrameFilters);
// INIT_STATIC_METHOD(IC_CreateFrameFilter);
// INIT_STATIC_METHOD(IC_AddFrameFilterToDevice);
// INIT_STATIC_METHOD(IC_RemoveFrameFilterFromDevice);
// INIT_STATIC_METHOD(IC_DeleteFrameFilter);
// INIT_STATIC_METHOD(IC_FrameFilterShowDialog);
// INIT_STATIC_METHOD(IC_FrameFilterGetParameter);
// INIT_STATIC_METHOD(IC_FrameFilterSetParameterInt);
// INIT_STATIC_METHOD(IC_FrameFilterSetParameterFloat);
// INIT_STATIC_METHOD(IC_FrameFilterSetParameterBoolean);
// INIT_STATIC_METHOD(IC_FrameFilterSetParameterString);
// INIT_STATIC_METHOD(IC_FrameFilterDeviceClear);
// INIT_STATIC_METHOD(IC_enumCodecs);
// INIT_STATIC_METHOD(IC_Codec_Create);
// INIT_STATIC_METHOD(IC_Codec_Release);
// INIT_STATIC_METHOD(IC_Codec_getName);
// INIT_STATIC_METHOD(IC_Codec_hasDialog);
// INIT_STATIC_METHOD(IC_Codec_showDialog);
// INIT_STATIC_METHOD(IC_SetCodec);
// INIT_STATIC_METHOD(IC_SetAVIFileName);
// INIT_STATIC_METHOD(IC_enableAVICapturePause);
// INIT_STATIC_METHOD(IC_SetRingBufferSize);
// INIT_STATIC_METHOD(IC_GetRingBufferSize);
// INIT_STATIC_METHOD(IC_GetMemBuffer);
// INIT_STATIC_METHOD(IC_GetMemBufferLastAcq);
// INIT_STATIC_METHOD(IC_ReleaseMemBuffer);
// INIT_STATIC_METHOD(IC_GetMemBufferDescription);
// INIT_STATIC_METHOD(IC_MemBufferLock);
// INIT_STATIC_METHOD(IC_MemBufferisLocked);
// INIT_STATIC_METHOD(IC_MemBufferGetIndex);
// INIT_STATIC_METHOD(IC_MemBufferGetDataPtr);

Napi::Object Init(Napi::Env env, Napi::Object exports) {
    TISGrabber::Init(env, exports);
    return exports;
}

NODE_API_MODULE(ic_node, Init)

#else
#endif